name: kids_learning_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  path: ^1.8.0
  path_provider: ^2.1.2
  video_player: ^2.7.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.12
  lottie: ^2.7.0
  dio: ^5.4.0
  permission_handler: ^11.3.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/audio/
    - assets/images/
    - assets/animation/anime.json

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
